spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: hungsmilecrz15@gmail.com
    password: ckgrjsjekcysqryp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 267232145852-s6hhlfvg7ue4e6uumjdk68fcb1dcfin6.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          github:
            clientId: f3f20a42a26569979ff4
            clientSecret: 95d92b17760c670dead06cc5d64147a0e258821d
            scope:
              - user:email
              - read:user
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**

jwt:
  privateKey: Y68oPXSNa/HHkVhcBLLcUnMfxoB1WsIROZtqAnBOuDQ=

fileStorage:
  path: /Users/phamngochung/Desktop/food/src/main/resources/static/img