spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: hungsmilecrz15@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**

jwt:
  privateKey: Y68oPXSNa/HHkVhcBLLcUnMfxoB1WsIROZtqAnBOuDQ=

fileStorage:
  path: /Users/phamngochung/Desktop/food/src/main/resources/static/img